### ISSUE TITLE
Feature Request: Custom nock request body matching

### ISSUE THREAD

**Issue by MacMcIrish** [blackflux/lambda-tdd#83]
## Issue
Nock recordings are not picked up unless request body is explicitly matched, this is an issue when the nock recording contains generated body parameters.

Nock supports ignoring matching the request body, maybe this can be implemented?
https://github.com/node-nock/nock#protip

**Comment by simlu** [comment]
@jeff.soloshy Can you detail? How would this work? For now `"*"` for body seems to do the job?

**Comment by MacMcIrish** [comment]
* in combination with timestamp and seed works perfect
